export type Difficulty = "easy" | "moderate" | "hard" | "very_hard";

export interface SeedTopic {
  system: string;
  systemOrder: number;
  name: string;
  difficulty: Difficulty;
}

function sys(systemOrder: number, system: string, entries: [string, Difficulty][]): SeedTopic[] {
  return entries.map(([name, difficulty]) => ({ system, systemOrder, name, difficulty }));
}

// 17 systems, ~170 topics, straight from the 3-month USMLE Step 1 tracker.
// Order matters: this is the sequence the first-pass scheduler walks through,
// system by system (Biochem -> ... -> Biostats), matching how high scorers
// report studying: immersive by system during first pass, not scattered.
export const SEED_TOPICS: SeedTopic[] = [
  ...sys(1, "Biochemistry & Molecular Biology", [
    ["Amino acids & biochemical properties", "moderate"],
    ["Enzyme kinetics & inhibition", "moderate"],
    ["Glycolysis, gluconeogenesis & pyruvate", "hard"],
    ["TCA cycle & oxidative phosphorylation", "hard"],
    ["Fatty acid synthesis/oxidation & ketone bodies", "hard"],
    ["Glycogen metabolism & storage diseases", "hard"],
    ["Pentose phosphate pathway", "moderate"],
    ["Purine & pyrimidine metabolism", "moderate"],
    ["Urea cycle", "hard"],
    ["Vitamins & nutritional deficiencies", "very_hard"],
    ["DNA replication, repair & transcription", "hard"],
    ["Translation & post-translational processing", "hard"],
    ["Inheritance patterns & pedigree basics", "hard"],
    ["Chromosomal disorders & trinucleotide repeats", "hard"],
  ]),
  ...sys(2, "Cell Biology & General Pathology", [
    ["Cell injury, adaptation & death", "hard"],
    ["Inflammation & inflammatory mediators", "hard"],
    ["Wound healing & tissue repair", "moderate"],
    ["Hemodynamic disorders, edema & thrombosis", "hard"],
    ["Shock", "very_hard"],
    ["Neoplasia & cancer genetics", "very_hard"],
    ["Tumor suppressors & oncogenes", "very_hard"],
    ["Cell cycle & apoptosis", "hard"],
    ["Amyloidosis", "hard"],
  ]),
  ...sys(3, "Immunology", [
    ["Innate vs adaptive immunity", "moderate"],
    ["T-cell and B-cell function", "hard"],
    ["MHC & antigen presentation", "hard"],
    ["Complement pathways", "hard"],
    ["Hypersensitivity I-IV", "very_hard"],
    ["Primary immunodeficiencies", "very_hard"],
    ["Secondary immunodeficiency & HIV", "very_hard"],
    ["Autoimmune disease principles", "hard"],
    ["Transplantation & graft-versus-host disease", "hard"],
  ]),
  ...sys(4, "Microbiology", [
    ["Gram-positive cocci", "very_hard"],
    ["Gram-negative cocci", "hard"],
    ["Gram-positive bacilli", "hard"],
    ["Gram-negative bacilli", "very_hard"],
    ["Anaerobes", "hard"],
    ["Spirochetes", "hard"],
    ["Atypical bacteria", "hard"],
    ["Mycobacteria", "very_hard"],
    ["DNA viruses", "very_hard"],
    ["RNA viruses", "very_hard"],
    ["Fungi", "hard"],
    ["Protozoa", "hard"],
    ["Helminths", "hard"],
    ["Antibacterial mechanisms/resistance", "very_hard"],
  ]),
  ...sys(5, "Pharmacology", [
    ["Pharmacokinetics & pharmacodynamics", "hard"],
    ["Autonomic pharmacology", "very_hard"],
    ["Cholinergic drugs", "very_hard"],
    ["Adrenergic drugs", "very_hard"],
    ["Cardiovascular drugs", "very_hard"],
    ["Antiarrhythmics", "very_hard"],
    ["Diuretics", "very_hard"],
    ["Antimicrobials", "very_hard"],
    ["CNS drugs", "very_hard"],
    ["Antidepressants & antipsychotics", "very_hard"],
    ["Antiepileptic drugs", "hard"],
    ["Endocrine pharmacology", "very_hard"],
    ["Steroids", "hard"],
    ["Chemotherapy", "very_hard"],
    ["Toxicology & antidotes", "hard"],
  ]),
  ...sys(6, "Cardiovascular", [
    ["Cardiac cycle, pressure-volume loops & heart sounds", "very_hard"],
    ["ECG basics & interpretation", "very_hard"],
    ["Action potentials & conduction system", "hard"],
    ["Preload, afterload, contractility & cardiac output", "very_hard"],
    ["Hypertension", "hard"],
    ["Ischemic heart disease / MI", "very_hard"],
    ["Heart failure", "very_hard"],
    ["Arrhythmias", "very_hard"],
    ["Valvular heart disease", "hard"],
    ["Congenital heart disease", "hard"],
    ["Endocarditis", "hard"],
    ["Pericardial disease", "hard"],
    ["Shock & hemodynamics", "very_hard"],
  ]),
  ...sys(7, "Respiratory", [
    ["Pulmonary volumes & capacities", "hard"],
    ["V/Q relationships", "very_hard"],
    ["Oxygen-hemoglobin dissociation curve", "very_hard"],
    ["Obstructive lung disease", "very_hard"],
    ["Restrictive lung disease", "hard"],
    ["Asthma & COPD", "very_hard"],
    ["Pneumonia", "very_hard"],
    ["Pulmonary embolism", "very_hard"],
    ["Pulmonary hypertension", "hard"],
    ["ARDS", "hard"],
    ["Lung cancers", "hard"],
  ]),
  ...sys(8, "Renal", [
    ["GFR, renal blood flow & clearance", "very_hard"],
    ["Tubular transport", "very_hard"],
    ["RAAS", "very_hard"],
    ["Acid-base physiology", "very_hard"],
    ["Metabolic acidosis/alkalosis", "very_hard"],
    ["Respiratory compensation", "hard"],
    ["Diuretics", "very_hard"],
    ["Acute kidney injury", "hard"],
    ["Chronic kidney disease", "hard"],
    ["Nephritic syndromes", "very_hard"],
    ["Nephrotic syndromes", "very_hard"],
    ["Renal tubular disorders", "very_hard"],
  ]),
  ...sys(9, "Gastrointestinal", [
    ["GI physiology & motility", "hard"],
    ["Esophageal disorders", "moderate"],
    ["Peptic ulcer disease & H. pylori", "hard"],
    ["Malabsorption", "hard"],
    ["Inflammatory bowel disease", "very_hard"],
    ["Celiac disease", "hard"],
    ["Hepatitis & liver injury patterns", "very_hard"],
    ["Cirrhosis & portal hypertension", "very_hard"],
    ["Gallbladder & biliary disease", "hard"],
    ["Pancreatitis", "hard"],
    ["GI cancers", "hard"],
  ]),
  ...sys(10, "Endocrine", [
    ["Hypothalamic-pituitary physiology", "very_hard"],
    ["Pituitary disorders", "hard"],
    ["Thyroid physiology & labs", "very_hard"],
    ["Hyperthyroidism/hypothyroidism", "very_hard"],
    ["Thyroid nodules/cancers", "hard"],
    ["Adrenal cortex disorders", "very_hard"],
    ["Adrenal medulla disorders", "hard"],
    ["Diabetes mellitus", "very_hard"],
    ["DKA & HHS", "very_hard"],
    ["PTH, vitamin D & calcium regulation", "very_hard"],
    ["Hyper/hypoparathyroidism", "hard"],
  ]),
  ...sys(11, "Reproductive", [
    ["Male reproductive physiology", "hard"],
    ["Female reproductive physiology", "very_hard"],
    ["Menstrual cycle & hormones", "very_hard"],
    ["Pregnancy physiology", "very_hard"],
    ["Pregnancy complications", "very_hard"],
    ["Contraception", "hard"],
    ["Sexually transmitted infections", "hard"],
    ["Breast pathology", "hard"],
    ["Testicular pathology", "hard"],
  ]),
  ...sys(12, "Neurology & Neuroanatomy", [
    ["Neuroanatomy localization", "very_hard"],
    ["Spinal cord tracts & lesions", "very_hard"],
    ["Cranial nerves", "very_hard"],
    ["Brainstem syndromes", "very_hard"],
    ["Cerebral blood supply & stroke", "very_hard"],
    ["Seizures", "hard"],
    ["Headache disorders", "hard"],
    ["Movement disorders", "hard"],
    ["Demyelinating diseases", "very_hard"],
    ["Peripheral neuropathies", "hard"],
    ["Neuromuscular junction disorders", "hard"],
    ["Brain tumors", "hard"],
    ["Neurodegenerative diseases", "hard"],
  ]),
  ...sys(13, "Psychiatry & Behavioral Science", [
    ["Major psychiatric disorders", "hard"],
    ["Depression & bipolar disorder", "hard"],
    ["Schizophrenia & psychosis", "hard"],
    ["Anxiety, OCD & PTSD", "moderate"],
    ["Personality disorders", "moderate"],
    ["Substance intoxication/withdrawal", "very_hard"],
    ["Psychopharmacology", "very_hard"],
    ["Defense mechanisms", "moderate"],
    ["Developmental milestones", "hard"],
  ]),
  ...sys(14, "Hematology & Oncology", [
    ["Anemia approach & RBC indices", "very_hard"],
    ["Iron deficiency & anemia of chronic disease", "hard"],
    ["Hemolytic anemias", "very_hard"],
    ["Hemoglobinopathies", "very_hard"],
    ["Leukemias", "very_hard"],
    ["Lymphomas", "very_hard"],
    ["Multiple myeloma", "hard"],
    ["Platelet disorders", "hard"],
    ["Coagulation cascade", "very_hard"],
    ["DIC, TTP & HUS", "very_hard"],
  ]),
  ...sys(15, "Musculoskeletal & Dermatology", [
    ["Bone tumors & metabolic bone disease", "hard"],
    ["Osteoporosis/osteomalacia/rickets", "hard"],
    ["Gout & pseudogout", "hard"],
    ["Rheumatoid arthritis & SLE", "very_hard"],
    ["Osteoarthritis", "moderate"],
    ["Myopathies", "hard"],
    ["Peripheral nerve injuries", "very_hard"],
    ["Common dermatologic infections", "moderate"],
    ["Vesiculobullous diseases", "hard"],
    ["Drug eruptions", "hard"],
    ["Skin cancers", "hard"],
  ]),
  ...sys(16, "Anatomy & Embryology", [
    ["Thorax anatomy", "hard"],
    ["Abdominal anatomy", "hard"],
    ["Pelvic anatomy", "very_hard"],
    ["Inguinal/femoral hernias", "hard"],
    ["Brachial plexus", "very_hard"],
    ["Upper/lower limb nerve lesions", "very_hard"],
    ["Cranial nerve anatomy", "very_hard"],
    ["Embryologic derivatives", "very_hard"],
    ["Congenital malformations", "hard"],
  ]),
  ...sys(17, "Biostatistics, Epidemiology & Ethics", [
    ["Sensitivity, specificity, PPV, NPV", "very_hard"],
    ["Likelihood ratios", "very_hard"],
    ["Relative risk & odds ratio", "hard"],
    ["Absolute/relative risk reduction", "very_hard"],
    ["NNT/NNH", "very_hard"],
    ["Study designs & bias", "hard"],
    ["Confidence intervals & p-values", "hard"],
    ["Screening principles", "hard"],
    ["Ethics & informed consent", "moderate"],
    ["Patient safety & communication", "moderate"],
  ]),
];

export const NBME_MILESTONES = [
  { name: "NBME 33", month: "december" as const },
  { name: "NBME 32", month: "december" as const },
  { name: "NBME 31", month: "december" as const },
  { name: "NBME 30", month: "january" as const },
  { name: "NBME 29", month: "january" as const },
  { name: "NBME 28", month: "january" as const },
];
